name: Semantic Versioning

on:
    push:
        branches:
            - main  # Modify this branch as needed

jobs:
    version:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v2
              with:
                  fetch-depth: 0  # Fetch all tags

            - name: Determine Previous Version
              id: get_previous_version
              run: |
                  # Determine the latest release version using git tags
                  latest_release_tag=$(git describe --tags --abbrev=0 2>/dev/null)
                  
                  if [ -z "$latest_release_tag" ]; then
                    previous_version="1.0.0"
                  else
                    previous_version=${latest_release_tag#v}
                  fi
                  echo "PREVIOUS_VERSION=$previous_version" >> $GITHUB_ENV

            - name: Check Commit Messages
              id: check_commits
              run: |
                  increment=""
                  if git log --format=%B -n 1 HEAD | grep -qE "^feat:"; then
                    increment="major"
                  elif git log --format=%B -n 1 HEAD | grep -qE "^fix:"; then
                    increment="minor"
                  elif git log --format=%B -n 1 HEAD | grep -qE "^docs:"; then
                    increment="patch"
                  fi
                  echo "INCREMENT=$increment" >> $GITHUB_ENV

            - name: Increment Version
              id: increment_version
              run: |
                  if [[ "$INCREMENT" == "major" ]]; then
                    VERSION=$(docker run --rm alpine/semver semver -c -i major $PREVIOUS_VERSION)
                  elif [[ "$INCREMENT" == "minor" ]]; then
                    VERSION=$(docker run --rm alpine/semver semver -c -i minor $PREVIOUS_VERSION)
                  elif [[ "$INCREMENT" == "patch" ]]; then
                    VERSION=$(docker run --rm alpine/semver semver -c -i patch $PREVIOUS_VERSION)
                  else
                    # If no increment found, use the previous version as is
                    echo "VERSION=$PREVIOUS_VERSION" >> $GITHUB_ENV
                  fi
                  echo "VERSION=$VERSION" >> $GITHUB_ENV

            - name: Configure git identity
              run: |
                  git config --global user.name "Paul P."
                  git config --global user.email "bigpaulie25ro@yahoo.com"

            - name: Display New Version
              run: |
                  echo "Previous version: $PREVIOUS_VERSION"
                  echo "New version: $VERSION"

            - name: Install hub
              run: |
                  sudo apt install hub

            - name: Create Tag
              env:
                  GITHUB_TOKEN: ${{ secrets.TOKEN }}
              run: |
                  git tag -a "$VERSION" -m "Release version $VERSION"
                  git push origin "$VERSION"