name: Tag on Commit
on:
    push:
        branches:
            - main

jobs:
    tag:
        runs-on: ubuntu-latest
        steps:
            - name: Check out the code
              uses: actions/checkout@v2

            - name: Determine version and create tag
              id: version-tag
              run: |
                  version=$(docker run --rm -v "$(pwd)":/app alpine/semver inc -p)
                  echo "VERSION=$version" >> $GITHUB_ENV

            - name: Create and push tag
              env:
                  GITHUB_TOKEN: ${{ secrets.TOKEN }}
              run: |
                  version=$VERSION
                  git tag "v$version"
                  git push origin "v$version"
